### PR TITLE
stored activation data as backend in the mysql db

### LINKED ISSUE #93: implement second-level storage for user approval
it is possible that redis crashes in production and all the data will be killed. that would be fatal because of pending activations, so we should add a second level storage such as mysql that stores the data, too, so if redis is down, the data can be kept still

### PR DESCRIPTION
**Pull request by Ma27**
resolves #93

### CODE REVIEW

File: src/AppBundle/Model/User/Registration/TwoStepRegistrationApproach.php [hunk 1]
```diff
@@ -305,8 +305,13 @@ private function findUserByActivationKeyAndUsername($activationKey, $username)
         $repository = $this->entityManager->getRepository('Account:User');
         $query      = ['activationKey' => $activationKey, 'username' => $username];
 
-        if ((!$user = $repository->findOneBy($query)) || $this->isActivationExpired($activationKey)) {
-            throw new UserActivationException();
+        if ((!$user = $repository->findOneBy($query))) {
```
Comment (Ma27) [inline src/AppBundle/Model/User/Registration/TwoStepRegistrationApproach.php]: one bracket pair is obsolete

File: src/AppBundle/Model/User/User.php [hunk 2]
```diff
@@ -492,6 +509,7 @@ public function removeRole(Role $role)
         }
 
         $this->roles->removeElement($role);
+        $this->pendingActivation = null;
```
Comment (Ma27) [inline src/AppBundle/Model/User/User.php]: wrong method I guess ;)
